# Generated by Django 5.2.8 on 2025-11-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=60)),
                ('post_author', models.TextField(max_length=10)),
                ('post_categor', models.TextField(max_length=10)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('post_content', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
